name: Welcome message for issues
on:
  issues:
    types:
      - opened
permissions:
  issues: write
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Output data
        run: |
         echo "Issue number: ${{ github.event.issue.number }}"
         echo "Issue author: ${{ github.event.issue.user.login }}"
         echo "Current repo: ${{ github.repository }}"
      - name: Say hi
        uses: jungwinter/comment@v1
        with:
          type: create
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          body: |
            Hi, ${{ github.event.issue.user.login }}! Welcome to ${{ github.repository }} issues! 
            Make sure to comply with the 
            [Code of Conduct](https://github.com/${{ github.repository }}/CODE_OF_CONDUCT.md).
