name: equal-lib CI

on:
  push:
    branches: [ main ]
    paths:
      - src/*.*
      - .github/workflows/main.yml
  pull_request:
    branches: [ main ]
    paths:
      - src/*.*
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
          always-auth: true
          registry-url: https://registry.npmjs.org
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Set auth token
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Build source code
        run: yarn build

      - name: Run test suites
        run: yarn test


      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
