name: Pull Request testing

on:  
  pull_request:
    branches: 
      - main
    paths:
      - src/**/*.*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install dependencies
        run: yarn
      - name: Check for modified files 
        run: |
         if /usr/bin/git diff --name-only HEAD~ HEAD | grep -qE 'tests/|\.md$'; then
          echo "Error: You've changed files you're not allowed to!"
          exit 1
         fi
      - name: Test code
        run: yarn test